# Generated by Django 5.2.11 on 2026-02-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='service_provider',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='village',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='fpo',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assistant',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fpoapp.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpoapp.fpo'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fpo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpoapp.fpo'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpoapp.farmer'),
        ),
    ]
